CZE.Web/Areas/AdministrativniRadnik/Controllers/KursKategorijaController.cs
using CZE.Data;
using CZE.Data.Models;
using CZE.Web.Areas.AdministrativniRadnik.Models;
using CZE.Web.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CZE.Web.Areas.AdministrativniRadnik.Controllers
{
    [Autorizacija(UlogeKorisnika.Administrativni_Radnik, UlogeKorisnika.Direktor, UlogeKorisnika.Administrator)]
    public class KursKategorijaController : Controller
    {
        CZEContext db = new CZEContext();

        public ActionResult Main()
        {
            if (TempData["InfoMessage"] != null)
                ViewBag.InfoMessage = TempData["InfoMessage"];
            var k = new KursKategorijaVM();
            k.KursKategorije = db.KursKategorije.AsNoTracking().ToList();
            return View(k);
        }
        public PartialViewResult _Create()
        {
            return PartialView("_Create");
        }
        [HttpPost]
        public ActionResult Create(KursKategorijaVM model)
        {
            if (ModelState.IsValid)
            {
                db.KursKategorije.Add(model.ToKursKategorija());
                try
                {
                    db.SaveChanges();
                    TempData["InfoMessage"] = new InfoMessage("Kategorija kursa '" + model.Naziv + "' uspješno pohranjena u bazu.", InfoMessageType.success);
                    return RedirectToAction("Main");
                }
                catch (Exception)
                {
                }
            }
            TempData["InfoMessage"] = new InfoMessage("Kategorija kursa nije pohranjena u bazu.", InfoMessageType.danger);

            return RedirectToAction("Main");
        }
        public PartialViewResult _Edit(int id)
        {
            KursKategorija kk = db.KursKategorije.Find(id);
            KursKategorijaVM kkVM = new KursKategorijaVM();
            kkVM.KursKategorijaID = kk.KursKategorijaID;
            kkVM.Naziv = kk.Naziv;
            return PartialView("_Edit", kkVM);
        }
        [HttpPost]
        public ActionResult Edit(KursKategorijaVM model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    KursKategorija kk = model.ToKursKategorija();
                    db.KursKategorije.Attach(kk);
                    db.Entry(kk).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    TempData["InfoMessage"] = new InfoMessage("Kategorija kursa '" + model.Naziv + "' uspješno editovana.", InfoMessageType.success);
                }
                catch (Exception)
                {
                    TempData["InfoMessage"] = new InfoMessage("Kategorija kursa '" + model.Naziv + "' nije editovana.", InfoMessageType.danger);
                }
            }
            else
            {
                TempData["InfoMessage"] = new InfoMessage("Kategorija kursa '" + model.Naziv + "' nije editovana.", InfoMessageType.danger);
            }
            return RedirectToAction("Main");
        }
        public ActionResult Delete(int id)
        {
            if (!db.KursTipovi.Any(x => x.KursKategorijaID == id))
            {
                try
                {
                    KursKategorija k = new KursKategorija { KursKategorijaID = id };
                    db.KursKategorije.Attach(k);
                    db.KursKategorije.Remove(k);
                    db.SaveChanges();
                    TempData["InfoMessage"] = new InfoMessage("Kategorija kursa izbrisana.", InfoMessageType.success);
                    return RedirectToAction("Main");
                }
                catch (Exception)
                {

                }
            }
            TempData["InfoMessage"] = new InfoMessage("Kategoriju kursa nije moguće obrisati.", InfoMessageType.danger);

            return RedirectToAction("Main");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CZE.Web/Areas/AdministrativniRadnik/Views/KursKategorija/Main.cshtml
@model CZE.Web.Areas.AdministrativniRadnik.Models.KursKategorijaVM
@{
    ViewBag.Title = "KursKategorijaCreate";
    Layout = "~/Views/Shared/_SB_Admin2.cshtml";
    CZE.Web.Helper.InfoMessage InfoMessage = ViewBag.InfoMessage;
}

<h2>Kategorije kursa</h2>
<hr />
@if (InfoMessage != null)
{
    <div class='alert alert-@InfoMessage.Tip alert-dismissable'>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <strong>@InfoMessage.Message</strong>
        <br />
    </div>
}
<!-- Button trigger modal -->
<button id="modalBTN" type="button" data-toggle="modal" data-target="#myModal" hidden></button>


<div class="col-md-5 row">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="list-group text-center">
                    <p class="list-group-item active">

                        @Ajax.ActionLink("Nova kategorija", "_Create", "KursKategorija",
                            routeValues: null,
                            ajaxOptions: new AjaxOptions { UpdateTargetId = "mEdit", OnSuccess = "ShowModal" },
                            htmlAttributes: new { @class = "btn btn-primary ", title = "Kurs kategorija create" })
                    </p>

                    <table width="100%">
                        @foreach (var item in Model.KursKategorije)
                        {
                            <tr>
                                <td>
                                    <a class="list-group-item clearfix" href="/AdministrativniRadnik/KursTip/KursTipCreate?kursKategorijaID=@item.KursKategorijaID">
                                        @item.Naziv
                                    </a>
                                </td>
                                <td width="20%">
                                    @Ajax.ActionLink(" ", "_Edit", routeValues: new { id = item.KursKategorijaID },
                                    ajaxOptions: new AjaxOptions { UpdateTargetId = "mEdit", OnSuccess = "ShowModal", HttpMethod = "GET" },
                                    htmlAttributes: new { @class = "glyphicon glyphicon-edit", style = "font-size:20px", title = "Edit" })
                                @Html.ActionLink(" ", "Delete", new { id = item.KursKategorijaID }, new { @class = "glyphicon glyphicon-remove", style = "font-size:20px", title = "Delete" })
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Create/Edit kategorija kursa</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="mEdit">

            </div>
        </div>
    </div>
</div>

@section JavaScriptFiles
{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script>
        function ShowModal() {
            $.validator.unobtrusive.parse("#EditForm");
            $("#modalBTN").click();
        };
    </script>
}

CZE.Web/Areas/AdministrativniRadnik/Views/KursKategorija/_Create.cshtml
@model CZE.Web.Areas.AdministrativniRadnik.Models.KursKategorijaVM
@using (Html.BeginForm("Create", "KursKategorija", FormMethod.Post, new {id="EditForm" }))
{
    <div class="modal-body text-center">
        @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control", PlaceHolder = "Naziv kategorije" } })
        @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Snimi</button>
    </div>
}

CZE.Web/Areas/AdministrativniRadnik/Views/KursKategorija/_Edit.cshtml
@model CZE.Web.Areas.AdministrativniRadnik.Models.KursKategorijaVM
@using (Html.BeginForm("Edit", "KursKategorija", FormMethod.Post,new {id="EditForm" }))
{
    @Html.HiddenFor(model=>model.KursKategorijaID)
    <div class="modal-body text-center">
        @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control", PlaceHolder = "Naziv kategorije" } })
        @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Snimi</button>
    </div>
}