CZE.Web/Areas/AdministrativniRadnik/Controllers/UplataKandidataController.cs
using CZE.Data;
using CZE.Web.Areas.AdministrativniRadnik.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using CZE.Data.Models;
using CZE.Web.Helper;
namespace CZE.Web.Areas.AdministrativniRadnik.Controllers
{
    [Autorizacija(UlogeKorisnika.Administrativni_Radnik, UlogeKorisnika.Direktor, UlogeKorisnika.Administrator)]
    public class UplataKandidataController : Controller
    {
        CZEContext db = new CZEContext();
        public ActionResult Initial()
        {
            List<Data.Models.Kandidat> kandidati = db.Kandidats.AsNoTracking().Include(x => x.Osoba).ToList();
            List<UplataKandidataTableVM> kandidatiTable = new List<UplataKandidataTableVM>();
            foreach (var item in kandidati)
            {
                kandidatiTable.Add(new UplataKandidataTableVM(item));
            }
            return View(kandidatiTable);
        }
        public PartialViewResult GrupeKandidata(int kandidatId)
        {
            List<GrupeKandidatiTableVM> grupe = db.GrupeKandidati
                .AsNoTracking()
                .Where(x => x.KandidatID == kandidatId)
                .Select(s => new GrupeKandidatiTableVM
                {
                    GrupaKandidatiID = s.GrupaKandidatiID,
                    GrupaNaziv = s.Grupa.Naziv,
                    KursNaziv = s.Grupa.Kurs.Naziv,
                    TipNaziv = s.Grupa.Kurs.KursTip.Naziv,
                    Predavac = s.Grupa.Zaposlenik.Osoba.Ime + " " + s.Grupa.Zaposlenik.Osoba.Prezime,
                    Uplaceno = (!s.UplateKandidata.Any() ? 0m : s.UplateKandidata.Sum(x => x.Kolicina)) + "\\" + s.Grupa.Kurs.KursTip.Cijena + " KM",
                    StatusUplate = s.UplateKandidata.Any(x => x.StatusUplate == true)
                }).ToList();

            if (TempData["InfoMessage"] != null)
                ViewBag.InfoMessage = TempData["InfoMessage"];
            return PartialView("_GrupaKandidatiTable", grupe);
        }
        public ActionResult Create(int grupaKandidatiId = 0)
        {
            UplataKandidataEditVM model = new UplataKandidataEditVM();
            model.NavGrupaKandidatiID = grupaKandidatiId;
            model.DatumUplate = DateTime.Now;
            model.GrupaKandidatiDDL = UplataKandidataEditVM.GrupaKandidatiDDLSet(db, grupaKandidatiId);

            return View("_Create", model);
        }
        [HttpPost]
        public ActionResult Create(UplataKandidataEditVM model)
        {
            if (!ModelState.IsValid)
            {
                model.GrupaKandidatiDDL = UplataKandidataEditVM.GrupaKandidatiDDLSet(db, model.GrupaKandidatiID);
                return View("_Create", model);
            }

            int logiraniKorisnikId = Autentifikacija.GetLogiraniKorisnik(HttpContext).KorisnickiNalogID;
            if (db.Zaposlenici.Any(x => x.ZaposlenikID == logiraniKorisnikId))
            {
                try
                {
                    UplataKandidata uplata = model.ToUplataKandidata();
                    uplata.ZaposlenikID = logiraniKorisnikId;
                    db.UplateKandidata.Add(uplata);
                    db.SaveChanges();
                    TempData["InfoMessage"] = new InfoMessage("Uplata uspješno pohranjena u bazu.", InfoMessageType.success);
                }
                catch (Exception)
                {
                    TempData["InfoMessage"] = new InfoMessage("Uplata nije pohranjena u bazu.", InfoMessageType.danger);
                }
            }
            else
            {
                TempData["InfoMessage"] = new InfoMessage("Logirani korisnik mora biti zaposlenik da bih dodao uplatu.", InfoMessageType.warning);
            }

            int kandidatID = GetKandidatIdByGrupaKandidatiId(model.GrupaKandidatiID);
            return RedirectToAction("UplateGrupaKandidat", new { grupaKandidatiId = model.GrupaKandidatiID });
        }
        public int GetKandidatIdByGrupaKandidatiId(int grupaKandidatiID)
        {
            return db.GrupeKandidati.AsNoTracking()
                .Where(x => x.GrupaKandidatiID == grupaKandidatiID)
                .FirstOrDefault()
                .KandidatID;
        }
        public ActionResult UplateGrupaKandidat(int grupaKandidatiId = 0)
        {
            UplateGrupaKandidatiVM uplateVM = new UplateGrupaKandidatiVM();
            uplateVM.GrupaKandidatiID = grupaKandidatiId;
            uplateVM.KandidatID = GetKandidatIdByGrupaKandidatiId(grupaKandidatiId);

            var customSelect = db.GrupeKandidati
                 .AsNoTracking()
                 .Where(x => x.GrupaKandidatiID == grupaKandidatiId)
                 .Select(s => new
                 {
                     grupaDetails = s.Grupa.Naziv + "|" + s.Grupa.Kurs.Naziv + "|" + s.Grupa.Kurs.KursTip.Naziv,
                     kandidatDetails = s.Kandidat.Osoba.Ime + " " + s.Kandidat.Osoba.Prezime,
                     uplataDetails = (!s.UplateKandidata.Any() ? 0m : s.UplateKandidata.Sum(x => x.Kolicina)) + "\\" + s.Grupa.Kurs.KursTip.Cijena + " KM"
                 }).FirstOrDefault();

            uplateVM.GrupaDetails = customSelect.grupaDetails;
            uplateVM.KandidatDetails = customSelect.kandidatDetails;
            uplateVM.UplataDetails = customSelect.uplataDetails;

            uplateVM.UplateKandidataTable = db.UplateKandidata
                .AsNoTracking()
                .Where(x => x.GrupaKandidatiID == grupaKandidatiId)
                .OrderByDescending(x => x.DatumUplate)
                .ToList();
            if (TempData["InfoMessage"] != null)
                ViewBag.InfoMessage = TempData["InfoMessage"];
            return PartialView("_UplateGrupaKandidat", uplateVM);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CZE.Web/Areas/AdministrativniRadnik/Views/UplataKandidata/Initial.cshtml
@model IEnumerable<CZE.Web.Areas.AdministrativniRadnik.Models.UplataKandidataTableVM>
@{
    ViewBag.Title = "Initial";
    Layout = "~/Views/Shared/_SB_Admin2.cshtml";
}
@section HeadLinks
{
    <link href="https://cdn.datatables.net/1.10.13/css/dataTables.bootstrap.min.css" rel="stylesheet" />
}
<h2>Uplate kandidata</h2>
<hr />
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <table id="kandidatiTable" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.ImePrezime)</th>
                            <th>@Html.DisplayNameFor(model => model.Email)</th>
                            <th>@Html.DisplayNameFor(model => model.DatumRodjenja)</th>
                            <th>@Html.DisplayNameFor(model => model.DatumUpisa)</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.ImePrezime)</td>
                                <td>@Html.DisplayFor(modelItem => item.Email)</td>
                                <td>@Html.DisplayFor(modelItem => item.DatumRodjenja)</td>
                                <td>@Html.DisplayFor(modelItem => item.DatumUpisa)</td>
                                <td>
                                    @Ajax.ActionLink(" ", "GrupeKandidata", "UplataKandidata",
                                    routeValues: new { kandidatId = item.KandidatID },
                                    ajaxOptions: new AjaxOptions { UpdateTargetId = "grupeKandidata", OnSuccess = "SetTable" },
                                    htmlAttributes: new
                                    {
                                        @class = "glyphicon glyphicon-th-list",
                                        style = "font-size:20px",
                                        title = "Grupe",
                                    })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div id="grupeKandidata">

</div>
@section JavaScriptFiles
{
    <script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#kandidatiTable').DataTable({
                responsive: true,
                bInfo: false
            });
        });
        function SetTable() {
            $('#grupeKandidataTable').DataTable({
                responsive: true,
                bLengthChange: false,
                bFilter: false,
                bInfo: false
            });
            ScrollToTable();
        };
        function ScrollToTable() {
            $('html, body').animate({
                scrollTop: $("#grupeKandidata").offset().top
            }, 1000);
        };

        function ValidateForm() {
            $.validator.unobtrusive.parse("#form0");
            ScrollToTable();
        };
    </script>
}

CZE.Web/Areas/AdministrativniRadnik/Views/UplataKandidata/_Create.cshtml
@model CZE.Web.Areas.AdministrativniRadnik.Models.UplataKandidataEditVM

<div class="panel panel-primary">
    <div class="panel-heading">
        Unos uplate kandidata
    </div>
    <div class="panel-body">
        @using (Ajax.BeginForm(new AjaxOptions { UpdateTargetId = "grupeKandidata" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.UplataKandidataID)
                <div class="form-group">
                    @Html.LabelFor(model => model.GrupaKandidatiID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.DropDownListFor(model => model.GrupaKandidatiID, Model.GrupaKandidatiDDL, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.GrupaKandidatiID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Kolicina, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        <div class="input-group">
                            <span class="input-group-addon">KM</span>
                            @Html.EditorFor(model => model.Kolicina, new { htmlAttributes = new { @class = "form-control" } })
                            <span class="input-group-addon">,00</span>
                        </div>
                        @Html.ValidationMessageFor(model => model.Kolicina, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.DatumUplate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.DatumUplate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DatumUplate, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.StatusUplate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.StatusUplate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.StatusUplate, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.RacunIzdat, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.RacunIzdat, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RacunIzdat, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Biljeske, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.Biljeske, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Biljeske, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-4">
                        <input type="submit" value="Snimi" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
        @Ajax.ActionLink(" ", "UplateGrupaKandidat",
                                    routeValues: new { grupaKandidatiId = Model.NavGrupaKandidatiID },
                                             ajaxOptions: new AjaxOptions { UpdateTargetId = "grupeKandidata", OnSuccess = "ScrollToTable" },
                                                 htmlAttributes: new { @class = "glyphicon glyphicon-list-alt", style = "font-size:20px", title = "Pregled uplata" })
    </div>
</div>

CZE.Web/Areas/AdministrativniRadnik/Views/UplataKandidata/_GrupaKandidatiTable.cshtml
@model IEnumerable<CZE.Web.Areas.AdministrativniRadnik.Models.GrupeKandidatiTableVM>
@{
    CZE.Web.Helper.InfoMessage InfoMessage = ViewBag.InfoMessage;
}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Grupe kandidata
            </div>
            <div class="panel-body">
                @if (InfoMessage != null)
                {
                    <div class='alert alert-@InfoMessage.Tip alert-dismissable'>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <strong>@InfoMessage.Message</strong>
                        <br />
                    </div>
                }
                <table id="grupeKandidataTable" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.GrupaNaziv)</th>
                            <th>@Html.DisplayNameFor(model => model.KursNaziv)</th>
                            <th>@Html.DisplayNameFor(model => model.TipNaziv)</th>
                            <th>@Html.DisplayNameFor(model => model.Predavac)</th>
                            <th title="uplačeno\cijena kursa">@Html.DisplayNameFor(model => model.Uplaceno)</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.GrupaNaziv)</td>
                                <td>@Html.DisplayFor(modelItem => item.KursNaziv)</td>
                                <td>@Html.DisplayFor(modelItem => item.TipNaziv)</td>
                                <td>@Html.DisplayFor(modelItem => item.Predavac)</td>
                                <td>@Html.DisplayFor(modelItem => item.Uplaceno)</td>
                                <td>
                                    @Ajax.ActionLink(" ", "Create",
                                    routeValues: new { grupaKandidatiId = item.GrupaKandidatiID },
                                    ajaxOptions: new AjaxOptions { UpdateTargetId = "grupeKandidata", OnSuccess = "ValidateForm" },
                                    htmlAttributes: new { @class = "glyphicon glyphicon-plus-sign", style = "font-size:22px", title = "Dodaj uplatu" })
                                    
                                    @Ajax.ActionLink(" ", "UplateGrupaKandidat",
                                    routeValues: new { grupaKandidatiId = item.GrupaKandidatiID },
                                 ajaxOptions: new AjaxOptions { UpdateTargetId = "grupeKandidata", OnSuccess = "ScrollToTable" },
                                    htmlAttributes: new { @class = "glyphicon glyphicon-list-alt", style = "font-size:20px", title = "Pregled uplata" })
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

CZE.Web/Areas/AdministrativniRadnik/Views/UplataKandidata/_UplateGrupaKandidat.cshtml
@model CZE.Web.Areas.AdministrativniRadnik.Models.UplateGrupaKandidatiVM
@{
    CZE.Web.Helper.InfoMessage InfoMessage = ViewBag.InfoMessage;
}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                @Ajax.ActionLink(" ", "Create",
                                    routeValues: new { grupaKandidatiId = Model.GrupaKandidatiID },
                                    ajaxOptions: new AjaxOptions { UpdateTargetId = "grupeKandidata", OnSuccess = "ValidateForm" },
                                    htmlAttributes: new { @class = "btn btn-default glyphicon glyphicon-plus", title = "Dodaj uplatu" })
                Uplate kandidata: <strong>@Model.KandidatDetails </strong> , za grupu <strong>@Model.GrupaDetails</strong> 
            </div>
            <div class="panel-body">
                @if (InfoMessage != null)
                {
                    <div class='alert alert-@InfoMessage.Tip alert-dismissable'>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <strong>@InfoMessage.Message</strong>
                        <br />
                    </div>
                }
                <table class="table table-striped table-hover">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.UplateKandidataTable[0].DatumUplate)</th>
                        <th>@Html.DisplayNameFor(model => model.UplateKandidataTable[0].Kolicina)</th>
                        <th>Otplačeno</th>
                        <th>Račun izdat</th>
                        <th>@Html.DisplayNameFor(model => model.UplateKandidataTable[0].Biljeske)</th>
                    </tr>

                    @foreach (var item in Model.UplateKandidataTable)
                    {
                        <tr>
                            <td>@String.Format("{0:dd.MM.yyyy}", item.DatumUplate)</td>
                            <td>@String.Format("{0:C}", item.Kolicina)</td>
                            <td>@Html.DisplayFor(modelItem => item.StatusUplate)</td>
                            <td>@Html.DisplayFor(modelItem => item.RacunIzdat)</td>
                            <td>@Html.DisplayFor(modelItem => item.Biljeske)</td>
                        </tr>
                    }
                </table>
                <span class="pull-right">Uplačeno: <strong>@Model.UplataDetails</strong></span>
                @Ajax.ActionLink(" ", "GrupeKandidata", "UplataKandidata",
                                    routeValues: new { kandidatId = Model.KandidatID },
                                    ajaxOptions: new AjaxOptions { UpdateTargetId = "grupeKandidata", OnSuccess = "SetTable" },
                                    htmlAttributes: new
                                    {
                                        @class = "glyphicon glyphicon-th-list",
                                        style = "font-size:20px",
                                        title = "Nazad na grupe",
                                    })
            </div>
        </div>
    </div>
</div>