CZE.Web/Controllers/AutentifikacijaController.cs
using CZE.Data;
using CZE.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using CZE.Web.Helper;
namespace CZE.Web.Controllers
{
    public class AutentifikacijaController : Controller
    {

        CZEContext db = new CZEContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Autentificate(string korisnickoIme, string lozinka, string zapamti)
        {
            LogiraniKorisnik lKorisnik = LogiraniKorisnik.LogiraniKorisnikGetByLogInInfoFromDatabase(db,korisnickoIme,lozinka);

            if (lKorisnik == null)
            {
                return RedirectToAction("Index");
            }
            Autentifikacija.PokreniNovuSesiju(lKorisnik, HttpContext, (zapamti == "on"));
            return RedirectToAction("Index", "Home");
        }
        public ActionResult Logout()
        {
            Autentifikacija.PokreniNovuSesiju(null, HttpContext, true);
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CZE.Web/Views/Autentifikacija/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Log in page</title>

    <!-- Bootstrap Core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Prijavi se</h3>
                    </div>
                    <div class="panel-body">

                        @using (Html.BeginForm("Autentificate", "Autentifikacija", FormMethod.Get))
                        {
                            <div class="form-group">
                                <input id="korisnickoIme" name="korisnickoIme" class="form-control" placeholder="Korisnicko ime ili E-mail" required autofocus>
                            </div>
                            <div class="form-group">
                                <input id="lozinka" name="lozinka" class="form-control" placeholder="Lozinka" type="password" required value="">
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input id="zapamti" name="zapamti" type="checkbox">Zapamti me
                                </label>
                            </div>

                            <input type="submit" value="Prijavi se" class="btn btn-lg btn-primary btn-block">
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>



</body>

</html>