CZE.Web/Areas/AdministrativniRadnik/Controllers/GrupaController.cs
using CZE.Data;
using CZE.Data.Models;
using CZE.Web.Areas.AdministrativniRadnik.Models;
using CZE.Web.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CZE.Web.Areas.AdministrativniRadnik.Controllers
{
    [Autorizacija(UlogeKorisnika.Administrativni_Radnik, UlogeKorisnika.Direktor, UlogeKorisnika.Administrator)]
    public class GrupaController : Controller
    {
        CZEContext db = new CZEContext();
        public ActionResult Create(int kursId = 0)
        {
            GrupaEditVM grupaVM = new GrupaEditVM();
            grupaVM.KursDDL = GrupaEditVM.KursDDLSet(db, kursId);
            grupaVM.PredavacDDL = GrupaEditVM.PredavaciDDLSet(db);
            grupaVM.KursID = kursId;
            grupaVM.Pocetak = DateTime.Now;
            return View(grupaVM);
        }
        [HttpPost]
        public ActionResult Create(GrupaEditVM model)
        {
            if (!ModelState.IsValid)
            {
                model.KursDDL = GrupaEditVM.KursDDLSet(db, model.KursID);
                model.PredavacDDL = GrupaEditVM.PredavaciDDLSet(db, model.ZaposlenikID);
                return View(model);
            }
            try
            {
                db.Grupe.Add(model.ToGrupa());
                db.SaveChanges();

            }
            catch (Exception)
            {
                ModelState.AddModelError(String.Empty, "Došlo je do greške prilikom validacije, provjeriti unesena polja.");
                model.KursDDL = GrupaEditVM.KursDDLSet(db, model.KursID);
                model.PredavacDDL = GrupaEditVM.PredavaciDDLSet(db, model.ZaposlenikID);
                return View(model);
            }
            TempData["InfoMessage"] = new InfoMessage("Grupa '" + model.Naziv + "' uspješno pohranjena u bazu.", InfoMessageType.success);

            return RedirectToAction("Prikaz", new { kursId = model.KursID });
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grupa k = db.Grupe.Find(id);
            if (k == null)
            {
                return HttpNotFound();
            }
            GrupaEditVM gVM = new GrupaEditVM(k);
            gVM.KursDDL = GrupaEditVM.KursDDLSet(db, gVM.KursID);
            gVM.PredavacDDL = GrupaEditVM.PredavaciDDLSet(db, gVM.ZaposlenikID);

            return View(gVM);
        }
        [HttpPost]
        public ActionResult Edit(GrupaEditVM model)
        {
            if (!ModelState.IsValid)
            {
                model.KursDDL = GrupaEditVM.KursDDLSet(db, model.KursID);
                model.PredavacDDL = GrupaEditVM.PredavaciDDLSet(db, model.ZaposlenikID);
                return View(model);
            }
            try
            {
                Grupa grupa = model.ToGrupa();
                db.Grupe.Attach(grupa);
                db.Entry(grupa).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            catch (Exception)
            {
                ModelState.AddModelError(String.Empty, "Došlo je do greške prilikom validacije, provjeriti unesena polja.");
                model.KursDDL = GrupaEditVM.KursDDLSet(db, model.KursID);
                model.PredavacDDL = GrupaEditVM.PredavaciDDLSet(db, model.ZaposlenikID);
                return View(model);
            }
            TempData["InfoMessage"] = new InfoMessage("Grupa '" + model.Naziv + "' uspješno editovana.", InfoMessageType.success);

            return RedirectToAction("Prikaz", new { kursId = model.KursID });
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GrupaDetailsVM details;
            details = db.Grupe
                .AsNoTracking()
                .Where(x => x.GrupaID == id)
                .Select(s => new GrupaDetailsVM
                {
                    Kurs = s.Kurs,
                    KursTip = s.Kurs.KursTip,
                    GrupaID = s.GrupaID,
                    Naziv = s.Naziv,
                    Pocetak = s.Pocetak,
                    Kraj = s.Kraj,
                    Aktivna = s.Aktivna,
                    KursID = s.KursID,
                    ImePrezimeZaposlenika = s.Zaposlenik.Osoba.Ime + " " + s.Zaposlenik.Osoba.Prezime
                })
                .FirstOrDefault();

            return View(details);
        }
        public ActionResult Prikaz(int? kursId)
        {
            if (kursId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (TempData["InfoMessage"] != null)
                ViewBag.InfoMessage = TempData["InfoMessage"];

            List<GrupaTableVM> list = db.Grupe
                .AsNoTracking()
                .Where(x => x.KursID == kursId)
                .Select(s => new GrupaTableVM
                {
                    GrupaID = s.GrupaID,
                    Naziv = s.Naziv,
                    Pocetak = s.Pocetak,
                    Kraj = s.Kraj,
                    Aktivna = s.Aktivna,
                    KursID = s.KursID
                })
                .ToList()
                .OrderByDescending(x => x.GrupaID)
                .ToList();

            ViewBag.kursId = kursId;
            var i = db.Kursevi
                .AsNoTracking()
                .Where(x => x.KursID == kursId)
                .Select(s => new { info = s.Naziv + "-" + s.KursTip.Naziv })
                .FirstOrDefault();
            ViewBag.kursInfo = i.info.ToString();
            return PartialView("_Prikaz", list);
        }
        public ActionResult StatusChange(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grupa k = db.Grupe.Find(id);
            if (k == null)
            {
                return HttpNotFound();
            }
            k.Aktivna = k.Aktivna ? false : true;
            try
            {
                db.SaveChanges();
            }
            catch (Exception) { }
            return RedirectToAction("Prikaz", new { kursId = k.KursID });
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grupa g = db.Grupe.Find(id ?? 0);
            if (g == null)
            {
                return HttpNotFound();
            }
            int kursId = g.KursID;
            if (!g.GrupaKandidati.Any())
            {
                try
                {
                    db.Grupe.Remove(g);
                    db.SaveChanges();
                    TempData["InfoMessage"] = new InfoMessage("Grupa '" + g.Naziv + "' je obrisana.", InfoMessageType.success);
                    return RedirectToAction("Prikaz", new { kursId = kursId });
                }
                catch (Exception)
                {

                }
            }
            TempData["InfoMessage"] = new InfoMessage("Grupu '" + g.Naziv + "' nije moguće obrisati.", InfoMessageType.danger);

            return RedirectToAction("Prikaz", new { kursId = kursId });
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CZE.Web/Areas/AdministrativniRadnik/Views/Grupa/Create.cshtml
@model CZE.Web.Areas.AdministrativniRadnik.Models.GrupaEditVM
@{
    ViewBag.Title = "Create";
    Layout = null;
}

<div class="panel panel-green">
    <div class="panel-heading">
        Grupa create
    </div>
    <div class="panel-body">
        @using (Ajax.BeginForm("Create", null,
    ajaxOptions: new AjaxOptions { UpdateTargetId = "grupaPrikaz", OnSuccess = "SetTableGrupa" },
    htmlAttributes: new { id = "grupaForm" }))
        {
            { Html.RenderPartial("_Create", Model); }
        }
        @Ajax.ActionLink(" ", "Prikaz", "Grupa",
                   routeValues: new { kursId = Model.KursID },
                   ajaxOptions: new AjaxOptions { UpdateTargetId = "grupaPrikaz", OnSuccess = "SetTableGrupa" },
                   htmlAttributes: new { @class = "glyphicon glyphicon-th-list", style = "font-size:20px", title = "Back to list" })
    </div>
</div>
<script>
    $(document).ready(function () {
        $.validator.unobtrusive.parse("#grupaForm");
    });
</script>

CZE.Web/Areas/AdministrativniRadnik/Views/Grupa/Details.cshtml
@model CZE.Web.Areas.AdministrativniRadnik.Models.GrupaDetailsVM
@{
    ViewBag.Title = "Details";
    Layout = null;
}

<div class="panel panel-green">
    <div class="panel-heading">
        Grupa details
    </div>
    <div class="panel-body">

        <div class="panel-group" id="accordion">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Tip kursa</a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse">
                    <div class="panel-body">
                        <div>
                            @{Html.RenderPartial("~/Areas/AdministrativniRadnik/Views/KursTip/_KursTipDetails.cshtml", Model.KursTip);}
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Kurs</a>
                    </h4>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse">
                    <div class="panel-body">
                        @{Html.RenderPartial("~/Areas/AdministrativniRadnik/Views/Kursevi/_KursDetails.cshtml", Model.Kurs);}
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">Grupa</a>
                    </h4>
                </div>
                <div id="collapseThree" class="panel-collapse collapse in">
                    <div class="panel-body">
                        @{Html.RenderPartial("~/Areas/AdministrativniRadnik/Views/Grupa/_GrupaDetails.cshtml", Model);}
                    </div>
                </div>
            </div>
        </div>
        <p>
            @Ajax.ActionLink(" ", "Edit",
        routeValues: new { id = Model.GrupaID },
        ajaxOptions: new AjaxOptions { UpdateTargetId = "grupaPrikaz" },
        htmlAttributes: new { @class = "glyphicon glyphicon-edit", style = "font-size:20px", title = "Edit" })
            @Ajax.ActionLink(" ", "Prikaz", "Grupa",
                routeValues: new { kursId = Model.KursID },
        ajaxOptions: new AjaxOptions { UpdateTargetId = "grupaPrikaz", OnSuccess = "SetTableGrupa" },
        htmlAttributes: new { @class = "glyphicon glyphicon-th-list", style = "font-size:20px", title = "Back to list" })
        </p>
    </div>
</div>

CZE.Web/Areas/AdministrativniRadnik/Views/Grupa/Edit.cshtml
@model CZE.Web.Areas.AdministrativniRadnik.Models.GrupaEditVM
@{
    ViewBag.Title = "Edit";
    Layout = null;
}

<div class="panel panel-green">
    <div class="panel-heading">
        Grupa edit
    </div>
    <div class="panel-body">
        @using (Ajax.BeginForm("Edit", null,
    ajaxOptions: new AjaxOptions { UpdateTargetId = "grupaPrikaz", OnSuccess = "SetTableGrupa" },
    htmlAttributes: new { id = "grupaForm" }))
        {
            { Html.RenderPartial("_Create", Model); }
        }
        @Ajax.ActionLink(" ", "Prikaz", "Grupa",
                   routeValues: new { kursId = Model.KursID },
                   ajaxOptions: new AjaxOptions { UpdateTargetId = "grupaPrikaz", OnSuccess = "SetTableGrupa" },
                   htmlAttributes: new { @class = "glyphicon glyphicon-th-list", style = "font-size:20px", title = "Back to list" })
    </div>
</div>
<script>
    $(document).ready(function () {
        $.validator.unobtrusive.parse("#grupaForm");

    });
</script>

CZE.Web/Areas/AdministrativniRadnik/Views/Grupa/_Create.cshtml
@model CZE.Web.Areas.AdministrativniRadnik.Models.GrupaEditVM

<div class="form-horizontal">
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.GrupaID)

    <div class="form-group">
        @Html.LabelFor(model => model.KursID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.DropDownListFor(model => model.KursID, Model.KursDDL,"Kurs", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.KursID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ZaposlenikID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.DropDownListFor(model => model.ZaposlenikID, Model.PredavacDDL,"Predavač", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ZaposlenikID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Pocetak, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.Pocetak, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Pocetak, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Kraj, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.Kraj, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Kraj, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
            <input type="submit" value="Snimi" class="btn btn-default" />
        </div>
    </div>
</div>

CZE.Web/Areas/AdministrativniRadnik/Views/Grupa/_GrupaDetails.cshtml
@model CZE.Web.Areas.AdministrativniRadnik.Models.GrupaDetailsVM

<div>
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Naziv)</dt>
        <dd>@Html.DisplayFor(model => model.Naziv)</dd>

        <dt>@Html.DisplayNameFor(model => model.Pocetak)</dt>
        <dd>@Html.DisplayFor(model => model.Pocetak)</dd>

        <dt>@Html.DisplayNameFor(model => model.Kraj)</dt>
        <dd>@Html.DisplayFor(model => model.Kraj)</dd>

        <dt>@Html.DisplayNameFor(model => model.Aktivna)</dt>
        <dd>@Html.DisplayFor(model => model.Aktivna)</dd>

        <dt>@Html.DisplayNameFor(model => model.ImePrezimeZaposlenika)</dt>
        <dd>@Html.DisplayFor(model => model.ImePrezimeZaposlenika)</dd>
    </dl>
</div>

CZE.Web/Areas/AdministrativniRadnik/Views/Grupa/_Prikaz.cshtml
@model IEnumerable<CZE.Web.Areas.AdministrativniRadnik.Models.GrupaTableVM>
@{
    CZE.Web.Helper.InfoMessage InfoMessage = ViewBag.InfoMessage;
}
<div class="panel panel-green">
    <div class="panel-heading">
        @Ajax.ActionLink(" ", "Create", "Grupa",
                 routeValues: new { kursId = Convert.ToInt32(ViewBag.kursId) },
                 ajaxOptions: new AjaxOptions { UpdateTargetId = "grupaPrikaz", OnSuccess = "ScrollToTableGrupa" },
                 htmlAttributes: new { @class = "btn btn-warning glyphicon glyphicon-plus", title = "Grupa create" })
        Grupe za kurs:<strong>@ViewBag.kursInfo</strong>
        <button id="toKursBTN" class="btn btn-warning pull-right"><span class="glyphicon glyphicon-arrow-up"></span></button>
    </div>
    <div class="panel-body">
        @if (InfoMessage != null)
        {
            <div class='alert alert-@InfoMessage.Tip alert-dismissable'>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <strong>@InfoMessage.Message</strong>
                <br />
            </div>
        }
        @if (Model.Count() > 0)
        {
            <table id="grupeTable" class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Naziv)</th>
                        <th>@Html.DisplayNameFor(model => model.Pocetak)</th>
                        <th>@Html.DisplayNameFor(model => model.Kraj)</th>
                        <th>@Html.DisplayNameFor(model => model.Aktivna)</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Naziv)</td>
                            <td>@Html.DisplayFor(modelItem => item.Pocetak)</td>
                            <td>@Html.DisplayFor(modelItem => item.Kraj)</td>
                            <td>
                                @Ajax.ActionLink(item.Aktivna ? "DA" : "NE", "StatusChange",
                                    routeValues: new { id = item.GrupaID },
                                 ajaxOptions: new AjaxOptions { UpdateTargetId = "grupaPrikaz" },
                                    htmlAttributes: new { @class = item.Aktivna ? "btn btn-success btn-xs" : "btn btn-danger btn-xs" })
                            </td>
                            <td class="text-right">
                                @Ajax.ActionLink(" ", "Edit",
                                    routeValues: new { id = item.GrupaID },
                                    ajaxOptions: new AjaxOptions { UpdateTargetId = "grupaPrikaz" },
                                    htmlAttributes: new { @class = "glyphicon glyphicon-edit", style = "font-size:20px", title = "Edit" })
                                @Ajax.ActionLink(" ", "Details",
                                    routeValues: new { id = item.GrupaID },
                                    ajaxOptions: new AjaxOptions { UpdateTargetId = "grupaPrikaz" },
                                    htmlAttributes: new { @class = "glyphicon glyphicon-list-alt", style = "font-size:20px", title = "Details" })
                                @Ajax.ActionLink(" ", "Delete",
                                routeValues: new { id = item.GrupaID },
                                 ajaxOptions: new AjaxOptions { UpdateTargetId = "grupaPrikaz" },
                              htmlAttributes: new { @class = "glyphicon glyphicon-remove", style = "font-size:20px", title = "Delete" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <div class='alert alert-warning alert-dismissable'>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <strong>Nema grupa za odabrani kurs.</strong>
                <br />
            </div>
        }

    </div>
</div>